remote_theme: pages-themes/minimal@v0.2.0
logo: docs/assets/Temp_headshot.png
title: Nicole Rouleau
email: nicole.r.rouleau@gmail.com
description: Economist | Data Analyst | Lifelong Learner

linkedin_url: "https://www.linkedin.com/in/nicole-rouleau/"
[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/nicole-rouleau/)

last_updated: false
