remote_theme: pages-themes/minimal@v0.2.0
logo: docs/assets/Temp_headshot.png
title: Nicole Rouleau
email: nicole.r.rouleau@gmail.com
description: Economist | Data Analyst | Lifelong Learner


last_updated: false
