remote_theme: pages-themes/minimal@v0.2.0
logo: docs/assets/Temp_headshot.png
title: Nicole Rouleau
email: nicole.r.rouleau@gmail.com
description: Economist | Data Analyst | Lifelong Learner

social_links:
  - { platform: github,   user_url: "https://github.com/nicolerouleau" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/nicolerouleau" 

last_updated: false
